site_name: AnyContext Docs
site_url: https://anycontext.io/docs
theme:
  name: material
  palette:
    scheme: slate
  logo: assets/android-chrome-192x192.png
  favicon: assets/favicon.ico
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true